apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: appmesh-grafana
  namespace: appmesh-system
spec:
  releaseName: appmesh-grafana
  chart:
    git: https://github.com/aws/eks-charts
    ref: master
    path: stable/appmesh-grafana
#  values:
#    image:
#      repository: 352684330888.dkr.ecr.us-west-2.amazonaws.com/amazon/app-mesh-controller
#      tag: latest
