apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: appmesh-inject
  namespace: appmesh-system
spec:
  releaseName: appmesh-inject
  chart:
    git: https://github.com/aws/eks-charts
    ref: master
    path: stable/appmesh-inject
  values:
    mesh:
      create: true
      name: "reinvent-2019"
      discovery: dns
    tracing:
      enabled: true
      provider: jaeger
      address: appmesh-jaeger.appmesh-system
      port: 9411
